### ISSUE TITLE
Using this component as a simple floating icon

### ISSUE THREAD

**Issue by simbolmina** [awran5/react-floating-whatsapp#13]
Hello,

Is there a way I can use this component as a simple floating icon that forwards users an external link so they can use WhatsApp web or WhatsApp app on mobile phones? I actually wrapped this component with an <a/> tag so I can use it this way, but the popup still opens and does not look good with my UI. I could add a simple icon to my app but it's a template that I don't know well and could not find a better icon than yours.

here is how it looks on the web page I'm working on: https://istanbul-yazilim.vercel.app/

**Comment by AppuYadav** [comment]
how to capture event on click whatsapp icon
