### ISSUE TITLE
Deactivate whatsapp button animation

### ISSUE THREAD

**Issue by Alex980102** [awran5/react-floating-whatsapp#14]
The problem is that when we want to run in safari with ios 16 the animation present a bug and i would like to be able to deactivate this animation.

At the bottom I show you a video of the problem

https://user-images.githubusercontent.com/74475326/196609540-b2057480-2aaa-4849-ab64-da9a611abc60.mp4

**Comment by awran5** [comment]
Hi @Alex980102 , Please try the latest version and let me know.

**Comment by Alex980102** [comment]
Hi @awran5 , i already check with version `5.0.5`  new version and the problem is still present

**Comment by awran5** [comment]
Hi @Alex980102, I guess its fixed now, please try v5.0.6 and let me know.
Thanks.

**Comment by Alex980102** [comment]
Thanks @awran5  `v5.0.6` works perfectly 😎
