### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by cristianregnier** [awran5/react-floating-whatsapp#15]
Hi @awran5 !

I'm getting the following error when trying to run v5.06 on React v18
```
> npm run start

Failed to compile.

./node_modules/react-floating-whatsapp/dist/index.js 285:43
Module parse failed: Unexpected token (285:43)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         children: A.jsxs("form", {
|           onSubmit: A => {
>             A.preventDefault(), gA.current?.value && (window.open(`https://api.whatsapp.com/send/?phone=${y}&text=${gA.current.value}`), K && K(A, gA.current.value), gA.current.value = "");
|           },
|           children: [A.jsx("input", {
```

The project was created using create-react-app. Until react-floating-whatsapp@4.x.x it works fine.

#### Component
```
import React from 'react';
import { FloatingWhatsApp } from 'react-floating-whatsapp';

export default function Demo() {
    return (
        <FloatingWhatsApp accountName='name' phoneNumber='1234567890' />
    )
}
```

#### Environment
| Package       | Version  |
|---------------|----------|
| node          | 14.17.1 |
| npm           | 8.16.0   |
| react         | 18.2.0   |
| react-scripts | 4.0.3    |

Thanks.

**Comment by awran5** [comment]
Hi @cristianregnier,  I guess you may need to upgrade `react-scripts` to [v5.0.1](https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md)

**Comment by cristianregnier** [comment]
Upgrading react-scripts to v5 did the trick. Thanks.

**Comment by awran5** [comment]
@cristianregnier  Thank you.
