### ISSUE TITLE
ChatBox is stuck at the bottom of the screen

### ISSUE THREAD

**Issue by tommytobi** [awran5/react-floating-whatsapp#3]
when you push the whastapp button the chatbox  is positioned to the botton no matter how high up you scroll. Instead of floating nexto the whatsapp button.

If you change the position from absolute to fixed for whatsappchatbox, the problem appears to resolve.

.floatingWhatsapp .whatsappChatBox {
...
    position: fixed;
...
  }

**Comment by awran5** [comment]
@ApathyElement Fixed. Thank you.
