### ISSUE TITLE
It isn’t working in apple devices

### ISSUE THREAD

**Issue by GabrielPMprog** [awran5/react-floating-whatsapp#34]
The button isn’t working in apple devices, when you click to send a message it returns a whatsapp page, that says to create a new contact. 
![IMG_1986](https://github.com/awran5/react-floating-whatsapp/assets/98840473/bdeffb5d-d279-40f5-9816-657a7d632b17)

**Comment by dgabel01** [comment]
Having the same issue, is there a workaround? Thanks in advance.

**Comment by GabrielPMprog** [comment]
Yes, I still have the same problem, the only alternative I found was to make a direct link, so i don't use the component

**Comment by dgabel01** [comment]
In a next.js project i added the following as prop and now it actually opens the whatsapp chat correctly on android and ios:

            onSubmit={() => window.open('whatsapp://send?phone=1234567890', '_self')}

**Comment by GabrielPMprog** [comment]
it works, thank you bro
