### ISSUE TITLE
The chat button is doing a zoom in apple devices 

### ISSUE THREAD

**Issue by GabrielPMprog** [awran5/react-floating-whatsapp#35]
Every time I click to write a message it gives a massive zoom and it only happens in apple devices, someone knows how to fix that ?

![IMG_2031](https://github.com/awran5/react-floating-whatsapp/assets/98840473/e2185b45-91c3-4ba0-876d-fb94c8c5b78b)

**Comment by danilopaiva** [comment]
@GabrielPMprog I have the same problem. how did you fix it?
Thanks!
