### ISSUE TITLE
Only green button background shown on Android (Chrome)

### ISSUE THREAD

**Issue by gecode-es** [awran5/react-floating-whatsapp#4]
The buttons white chat icon is invisible on Android (Chrome). Could this be a Fill colour issue with the SVG?

**Comment by awran5** [comment]
Hello @gecode-es 

Would you please check if this issue applied on this [sandbox](https://codesandbox.io/s/react-floating-whatsapp-183py) too? Here is a [direct](https://183py.csb.app/) link.
I just checked on my Android phone and I couldn't see the issue.

**Comment by gecode-es** [comment]
On my Android 10 the white chat icon is missing unfortunately.

![android](https://user-images.githubusercontent.com/8607281/123908168-55473e00-d977-11eb-841b-646430ee160d.jpg)

**Comment by gecode-es** [comment]
Submitted PR that will hopefully fix this. Be grateful if you could take a look.

**Comment by awran5** [comment]
Hello @gecode-es Thanks for help.
The issue is fixed now, please update to the latest version 1.5.0

**Comment by gecode-es** [comment]
Yes works great now on Android.
